spring:
#  datasource:
#    url:
#    username:
#    password:
#    driver-class-name:

  h2:
    console:
      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
      path: /h2-console  # H2 Console? Path
  # Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test  # H2 ?? ??
    username: kjy  # H2 ?? ? ??? username ?? (??? ??? ??)
    password: 1234 # H2 ?? ? ??? password ?? (??? ??? ??)


  # Spring Boot ??????? JPA ??
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
